import json
src=json.load(open('/tmp/atlas-world.geojson'))
rows=[('CAN','Canada','Northern America',-105,58,'United States lies to its south; Canada reaches into the Arctic.'),('USA','United States','Northern America',-100,39,'The contiguous states lie between Canada and Mexico; Alaska and Hawaii are separate.'),('MEX','Mexico','Central America',-102,24,'Mexico connects the southern North American mainland with Central America.'),('GTM','Guatemala','Central America',-90.3,15.5,'Guatemala lies immediately southeast of Mexico.'),('CUB','Cuba','Caribbean',-79.5,22,'Cuba is a long island south of Florida in the Caribbean.'),('BRA','Brazil','South America',-52,-12,'Brazil occupies much of eastern South America and reaches the Atlantic.'),('ARG','Argentina','South America',-64,-36,'Argentina lies east of the Andes in southern South America.'),('CHL','Chile','South America',-71,-30,'Chile forms a long Pacific strip along the western side of southern South America.'),('PER','Peru','South America',-75,-10,'Peru lies on the Pacific side of South America, north of Chile.'),('GBR','United Kingdom','Northern Europe',-2,54,'The UK includes Great Britain and Northern Ireland, off mainland northwestern Europe.'),('ESP','Spain','Southern Europe',-4,40,'Spain occupies most of the Iberian Peninsula, east of Portugal.'),('DEU','Germany','Western Europe',10,51,'Germany sits in central Europe between France and Poland.'),('ITA','Italy','Southern Europe',12.5,42,'Italy extends into the Mediterranean; its mainland is often compared to a boot.'),('NOR','Norway','Northern Europe',10,64,'Norway follows the Atlantic side of the Scandinavian Peninsula.'),('EGY','Egypt','Northern Africa',30,27,'Egypt occupies northeastern Africa and the Sinai Peninsula.'),('NGA','Nigeria','Western Africa',8,9,'Nigeria lies on the Gulf of Guinea in West Africa.'),('KEN','Kenya','Eastern Africa',38,0,'Kenya straddles the equator in East Africa and reaches the Indian Ocean.'),('ZAF','South Africa','Southern Africa',25,-29,'South Africa occupies the southern end of the African mainland.'),('IND','India','Southern Asia',79,22,'India extends southward between the Arabian Sea and Bay of Bengal.'),('CHN','China','Eastern Asia',104,35,'China spans a large part of eastern Asia with a Pacific coastline.'),('JPN','Japan','Eastern Asia',138,37,'Japan is an island chain east of the Asian mainland.'),('IDN','Indonesia','South-eastern Asia',117,-3,'Indonesia is an archipelago crossing the equator between Asia and Australia.'),('AUS','Australia','Australia and New Zealand',134,-25,'Australia lies south of Indonesia between the Indian and Pacific oceans.'),('NZL','New Zealand','Australia and New Zealand',173,-41,'New Zealand’s main islands lie southeast of Australia.')]
countries=[dict(code=r[0],name=r[1],region=r[2],lon=r[3],lat=r[4],description=r[5],id='country-'+r[0].lower()) for r in rows]
features=[]
for f in src['features']:
 p=f['properties']; code=p['ADM0_A3']; g=f['geometry']; polygons=g['coordinates'] if g['type']=='MultiPolygon' else [g['coordinates']]
 paths=[]
 for poly in polygons:
  for ring in poly:
   pts=[(round((x+180)*2,2),round((90-y)*2,2)) for x,y,*_ in ring]
   paths.append('M'+'L'.join(f'{x},{y}' for x,y in pts)+'Z')
 features.append(dict(code=code,path=''.join(paths)))
assert all(any(f['code']==c['code'] for f in features) for c in countries)
open('src/data/world.js','w').write('// Natural Earth 1:110m administrative geometry, public domain. Retrieved 2026-09-05.\nexport const shapes='+json.dumps(features,separators=(',',':'))+';\nexport const countries='+json.dumps(countries,ensure_ascii=False,separators=(',',':'))+';\n')
