import { lessonConnections } from "./data/lesson-connections.js";
// Original introductory lessons. Illustrative examples are labeled, not forecasts or personal advice.
export const areas = [
  [
    "history",
    "History",
    "How did we get here?",
    "Time, institutions and turning points.",
    "1789 → today",
  ],
  [
    "geography",
    "Geography",
    "Where changes everything.",
    "Read a world map, then look beneath its surface.",
    "180° W ↔ 180° E",
  ],
  [
    "science",
    "Science",
    "Follow the mechanism.",
    "Energy, matter and the waves connecting them.",
    "Observe → explain",
  ],
  [
    "civics",
    "Civics & Government",
    "Who can do what?",
    "A United States introduction to powers, laws and representation.",
    "Power ↔ limits",
  ],
  [
    "finance",
    "Personal Finance",
    "Small choices compound.",
    "Understand growth, borrowing and financial resilience.",
    "Today → later",
  ],
  [
    "tech",
    "Technology",
    "What happens behind the screen?",
    "Networks, instructions and the places data lives.",
    "Request → response",
  ],
  [
    "health",
    "Health Literacy",
    "Understand the evidence.",
    "Body systems, infection and the meaning of a health claim.",
    "Mechanism + context",
  ],
  [
    "economics",
    "Everyday Economics",
    "Choices have consequences.",
    "Production, prices and what we give up.",
    "Scarcity → choices",
  ],
  [
    "ai",
    "AI Literacy",
    "Prediction needs judgment.",
    "How models learn, generate and go wrong.",
    "Data → model → output",
  ],
  [
    "cyber",
    "Cybersecurity",
    "Make the next step safer.",
    "Identity, deceptive messages and resilient devices.",
    "Prevent · verify · recover",
  ],
  [
    "moons",
    "Moons & Planets",
    "Our neighborhood is enormous.",
    "Explore worlds, distances and the changing sky.",
    "0.39 → 30.07 AU",
  ],
  [
    "numbers",
    "Thinking with Numbers",
    "Make a number mean something.",
    "Percentages, chance and the evidence behind a claim.",
    "Compared with what?",
  ],
].map(([id, title, question, description, motif]) => ({
  id,
  title,
  question,
  description,
  motif,
}));
export const extraSources = {
  water: [
    "USGS · Water cycle",
    "https://www.usgs.gov/faqs/what-earths-water-cycle",
  ],
  plates: [
    "USGS · Plate tectonics",
    "https://pubs.usgs.gov/gip/volc/tectonics.html",
  ],
  latitude: [
    "NOAA · Latitude and longitude",
    "https://oceanservice.noaa.gov/facts/latitude.html",
  ],
  climate: [
    "NOAA · Ocean and climate",
    "https://oceanexplorer.noaa.gov/ocean-fact/climate/",
  ],
  energy: [
    "US Energy Information Administration · Energy explained",
    "https://www.eia.gov/energyexplained/what-is-energy/",
  ],
  dna: [
    "National Human Genome Research Institute · DNA",
    "https://www.genome.gov/about-genomics/fact-sheets/Deoxyribonucleic-Acid-Fact-Sheet",
  ],
  sky: [
    "NASA Space Place · Why is the sky blue?",
    "https://spaceplace.nasa.gov/blue-sky/en/",
  ],
  sound: [
    "NASA · Stellar sound waves",
    "https://science.nasa.gov/universe/exoplanets/symphony-of-stars-the-science-of-stellar-sound-waves/",
  ],
  branches: [
    "USA.gov · Branches of government",
    "https://www.usa.gov/branches-of-government",
  ],
  laws: [
    "USA.gov · How laws are made",
    "https://www.usa.gov/how-laws-are-made",
  ],
  constitution: [
    "National Archives · What does the Constitution say?",
    "https://www.archives.gov/founding-docs/constitution/what-does-it-say",
  ],
  electoral: [
    "National Archives · Electoral College",
    "https://www.archives.gov/electoral-college/about",
  ],
  compound: [
    "Investor.gov · Compound interest calculator",
    "https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator",
  ],
  apr: [
    "CFPB · Interest rates and APR",
    "https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-mortgage-interest-rate-and-an-apr-en-135/",
  ],
  credit: [
    "CFPB · Credit reports",
    "https://www.consumerfinance.gov/ask-cfpb/what-is-a-credit-report-en-309/",
  ],
  emergency: [
    "CFPB · Emergency funds",
    "https://www.consumerfinance.gov/an-essential-guide-to-building-an-emergency-fund/",
  ],
  diversify: [
    "Investor.gov · Diversification",
    "https://www.investor.gov/introduction-investing/investing-basics/save-and-invest/diversify-your-investments",
  ],
  network: [
    "MDN · How the Internet works",
    "https://developer.mozilla.org/en-US/docs/Learn_web_development/Howto/Web_mechanics/How_does_the_Internet_work",
  ],
  web: [
    "MDN · How the web works",
    "https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Web_standards/How_the_web_works",
  ],
  storage: [
    "MDN · Client-side storage",
    "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Client-side_APIs/Client-side_storage",
  ],
  algorithm: [
    "Khan Academy · Algorithms",
    "https://www.khanacademy.org/computing/computer-science/algorithms",
  ],
  vaccine: ["MedlinePlus · Vaccines", "https://medlineplus.gov/vaccines.html"],
  antibiotics: [
    "MedlinePlus · Antibiotics",
    "https://medlineplus.gov/antibiotics.html",
  ],
  heart: [
    "NHLBI · How the heart works",
    "https://www.nhlbi.nih.gov/health/heart",
  ],
  nutrition: [
    "FDA · Nutrition Facts label",
    "https://www.fda.gov/food/nutrition-facts-label/how-understand-and-use-nutrition-facts-label",
  ],
  testing: [
    "MedlinePlus · Understanding medical tests",
    "https://medlineplus.gov/lab-tests/how-to-understand-your-lab-results/",
  ],
  gdp: [
    "BEA · Gross domestic product",
    "https://www.bea.gov/data/gdp/gross-domestic-product",
  ],
  inflation: ["BLS · Consumer Price Index", "https://www.bls.gov/cpi/home.htm"],
  scarcity: [
    "Federal Reserve Bank of St. Louis · Opportunity cost",
    "https://www.stlouisfed.org/education/economic-lowdown-podcast-series/episode-1-opportunity-cost",
  ],
  demand: [
    "Federal Reserve Bank of St. Louis · Demand",
    "https://www.stlouisfed.org/education/economic-lowdown-podcast-series/episode-3-demand",
  ],
  supply: [
    "Federal Reserve Bank of St. Louis · Supply",
    "https://www.stlouisfed.org/education/economic-lowdown-podcast-series/episode-7-supply",
  ],
  training: [
    "Google · Overfitting",
    "https://developers.google.com/machine-learning/crash-course/overfitting/overfitting",
  ],
  genai: [
    "NIST · Generative AI risk profile",
    "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf",
  ],
  bias: [
    "NIST · Managing AI bias",
    "https://www.nist.gov/news-events/news/2022/03/theres-more-ai-bias-biased-data-nist-report-highlights",
  ],
  passwords: [
    "CISA · Strong passwords",
    "https://www.cisa.gov/secure-our-world/use-strong-passwords",
  ],
  mfa: [
    "CISA · Multifactor authentication",
    "https://www.cisa.gov/secure-our-world/turn-mfa",
  ],
  phishing: [
    "CISA · Recognize and report phishing",
    "https://www.cisa.gov/secure-our-world/recognize-and-report-phishing",
  ],
  updates: [
    "CISA · Update software",
    "https://www.cisa.gov/secure-our-world/update-software",
  ],
  sampling: [
    "NIST · Populations and sampling",
    "https://www.itl.nist.gov/div898/handbook/ppc/section1/ppc134.htm",
  ],
  causation: [
    "NIST · Experimental design",
    "https://www.itl.nist.gov/div898/handbook/ppc/section1/ppc136.htm",
  ],
  probability: [
    "OpenStax · Independent and mutually exclusive events",
    "https://openstax.org/books/introductory-statistics-2e/pages/3-2-independent-and-mutually-exclusive-events",
  ],
  percentages: [
    "OpenStax · Solve percent applications",
    "https://openstax.org/books/prealgebra-2e/pages/6-2-solve-general-applications-of-percent",
  ],
};
export const extraTopics = [],
  extraConcepts = [],
  extraPrompts = [];
// Each topic has an authored mechanism and at least two independently explained concepts.
function topic(area, id, title, question, type, scope, rows) {
  const items = rows.map((r) => r[0]);
  extraTopics.push({
    area,
    id,
    title,
    short: title,
    question,
    description: question,
    type,
    color: ["rust", "sage", "blue"][extraTopics.length % 3],
    range: [0, 1],
    scope,
    takeaway: rows[0][3],
    items,
  });
  rows.forEach(
    ([cid, label, summary, why, detail, steps, source, related, quiz], i) => {
      extraConcepts.push({
        id: cid,
        topic: id,
        title: label,
        label,
        year: 0,
        date: "A useful model",
        summary,
        why,
        detail,
        diagram: steps.split("|").map((s) => s.split("~")),
        diagramNote: scope,
        sources: source.split(","),
        related: [lessonConnections[cid]],
      });
      if (quiz) {
        const [question, answer, wrong1, wrong2, variant] = quiz;
        [question, variant].forEach((q, j) =>
          extraPrompts.push({
            id: cid + "-" + j,
            concept: cid,
            family: j ? "application" : "mechanism",
            question: q,
            options: j ? [wrong1, answer, wrong2] : [answer, wrong1, wrong2],
            answer: j ? 1 : 0,
            explanation: summary + " " + why,
            hint: steps.split("|")[0].split("~")[1],
          }),
        );
      }
    },
  );
}
topic(
  "geography",
  "changing-earth",
  "A moving, cycling planet",
  "How can solid ground move and water keep returning?",
  "cycle",
  "Schematic pathways, not a prediction of a local hazard.",
  [
    [
      "tectonic-plates",
      "Earth’s moving plates",
      "Earth’s outer rigid shell is divided into plates that move relative to one another.",
      "Most earthquakes and volcanoes cluster near plate boundaries.",
      "Plates can converge, separate or slide past each other. Some volcanoes occur within plates; a boundary map cannot predict the time of an earthquake.",
      "Diverge~Plates move apart|Converge~Plates come together|Transform~Plates slide sideways",
      "plates",
      "energy-transfer",
      [
        "Which motion describes a transform boundary?",
        "Sliding past",
        "Moving apart",
        "One plate disappearing instantly",
        "Two plates move sideways alongside one another. Which boundary is this?",
      ],
    ],
    [
      "water-cycle",
      "Water changes place and state",
      "Evaporation, condensation, precipitation and flows through land connect stores of water.",
      "The cycle has many routes and no single starting point.",
      "Water can remain in ice, groundwater or the ocean for very different lengths of time. The arrows describe transfers; they do not imply equal volumes or speeds.",
      "Evaporate~Liquid becomes vapor|Condense~Vapor forms droplets|Return~Precipitation and runoff redistribute water",
      "water",
      "ocean-climate",
      [
        "Which process turns water vapor into liquid droplets?",
        "Condensation",
        "Evaporation",
        "Runoff",
        "Cloud droplets form from vapor. Which process is involved?",
      ],
    ],
  ],
);
topic(
  "geography",
  "reading-earth",
  "Read the planet",
  "What do coordinates and oceans tell us?",
  "comparison",
  "Latitude is angular position, not temperature. Climate also depends on elevation, circulation and other factors.",
  [
    [
      "coordinates",
      "Two angles locate a place",
      "Latitude measures position north or south of the equator; longitude measures east or west of the prime meridian.",
      "The equator is 0° latitude. The prime meridian is 0° longitude.",
      "A complete coordinate pair needs both angles and their directions. Longitude lines meet at the poles, so one degree of longitude does not have a constant ground distance.",
      "Latitude~North or south, up to 90°|Longitude~East or west, up to 180°|Pair~Both are needed for a location",
      "latitude",
      "country-bra",
      [
        "Which coordinate tells north or south of the equator?",
        "Latitude",
        "Longitude",
        "Elevation",
        "A place is 30° north. Which angle does that describe?",
      ],
    ],
    [
      "ocean-climate",
      "The ocean moves heat",
      "The ocean absorbs and transports heat, influencing weather and climate.",
      "A place’s climate cannot be inferred from latitude alone.",
      "Currents redistribute heat. Water’s large heat capacity also moderates seasonal temperature changes near many coasts; actual local outcomes depend on circulation and geography.",
      "Absorb~Sunlight warms the ocean|Transport~Currents move heat|Exchange~Ocean and atmosphere interact",
      "climate",
      "water-cycle",
      [
        "Why can two places at a similar latitude have different climates?",
        "Ocean circulation and geography also matter",
        "Latitude measures rainfall directly",
        "All coastal places have identical climates",
        "Which helps explain a coast being milder than an inland place at the same latitude?",
      ],
    ],
  ],
);
topic(
  "science",
  "energy",
  "Energy changes form",
  "Where does the energy go?",
  "energy",
  "Illustrative energy transfers. Energy quantities are not measured values for a particular appliance.",
  [
    [
      "energy-transfer",
      "Energy is transferred, not used up",
      "Energy can move between objects and change form, while total energy is conserved in an isolated system.",
      "“Using energy” usually means converting it into forms less useful for the task.",
      "A moving bicycle slows as kinetic energy becomes thermal energy in brakes, tires and surroundings. The motion stops; the energy does not disappear.",
      "Input~Chemical or electrical energy|Useful output~Motion, light or another task|Other transfers~Often heat to surroundings",
      "energy",
      "compound-growth",
      [
        "When friction slows a bicycle, what happens to its kinetic energy?",
        "It becomes other forms, including heat",
        "It ceases to exist",
        "It all becomes extra mass",
        "Why does braking not violate conservation of energy?",
      ],
    ],
    [
      "efficiency",
      "Useful output is part of the input",
      "Efficiency compares useful energy output with total energy input for a defined task.",
      "A device can conserve energy overall while being inefficient at its job.",
      "If an illustrative device receives 100 joules and delivers 30 joules of useful light, its light efficiency is 30%. The other 70 joules are transferred in other forms.",
      "100 J~Total energy input|30 J~Useful light output|70 J~Other energy transfers",
      "energy",
      "percentage-points",
      [
        "A device makes 30 J of useful output from 100 J input. Its efficiency?",
        "30%",
        "70%",
        "130%",
        "How much of that device’s input became useful output?",
      ],
    ],
  ],
);
topic(
  "science",
  "living-code",
  "Information in living things",
  "What does DNA actually do?",
  "flow",
  "Simplified cellular information flow. Not all DNA encodes proteins, and traits can involve many genes and the environment.",
  [
    [
      "dna-information",
      "DNA stores biological information",
      "The sequence of bases in DNA carries information used by cells.",
      "A gene is a segment of DNA; DNA is not itself a miniature finished organism.",
      "Cells use portions of genetic information to make functional products. Many traits involve multiple genes as well as environmental influences.",
      "DNA~Information in a base sequence|RNA~A working molecular message|Protein~Many proteins perform cellular tasks",
      "dna",
      "ai-training",
      [
        "Where is information encoded in DNA?",
        "In the sequence of bases",
        "Only in the cell’s size",
        "In a tiny picture of the organism",
        "Two DNA molecules can carry different information because what differs?",
      ],
    ],
    [
      "genes-environment",
      "Genes are not the whole explanation",
      "Inherited variation can influence traits, but environment and interactions also matter.",
      "A genetic association alone is not a complete prediction of a person.",
      "For many complex traits, numerous variants contribute small effects. An introductory DNA diagram should not be read as a one-gene explanation for every human characteristic.",
      "Inheritance~Variants can differ|Environment~Conditions also differ|Trait~Outcomes may reflect both",
      "dna",
      "correlation",
      [
        "Why is “one gene determines every trait” misleading?",
        "Many traits involve multiple genes and environment",
        "DNA carries no information",
        "Environment changes every inherited base",
        "Why can a DNA result be an incomplete prediction of a complex trait?",
      ],
    ],
  ],
);
topic(
  "science",
  "waves",
  "Waves carry a change",
  "Why can we see sunlight but not hear space?",
  "comparison",
  "Sound is a mechanical wave; light is electromagnetic. The drawings compare mechanisms, not wavelengths to scale.",
  [
    [
      "sound-medium",
      "Sound needs a medium",
      "Sound travels through vibrations in matter such as air, water or solid material.",
      "A vacuum has no material to carry an ordinary sound wave.",
      "Space objects can contain vibrating matter, and measurements can be converted into audio. That does not mean sound travels unaided across the vacuum between Earth and a star.",
      "Source~Something vibrates|Medium~Matter transmits the disturbance|Receiver~Vibrations can be detected",
      "sound",
      "light-scattering",
      [
        "What does ordinary sound need to propagate?",
        "A material medium",
        "A perfect vacuum",
        "Sunlight",
        "Why does an airless gap block ordinary sound transmission?",
      ],
    ],
    [
      "light-scattering",
      "Short wavelengths scatter strongly",
      "Molecules in Earth’s atmosphere scatter shorter visible wavelengths more strongly than longer ones.",
      "Scattered sunlight reaching us from many directions makes the daytime sky appear blue.",
      "Near sunset, sunlight travels through more atmosphere. Much short-wavelength light is scattered out of the direct path, often leaving a redder view toward the Sun.",
      "Sunlight~Many visible wavelengths|Atmosphere~Short wavelengths scatter more|Observer~Receives scattered sky light",
      "sky",
      "ocean-climate",
      [
        "What helps explain a blue daytime sky?",
        "Atmospheric scattering of sunlight",
        "The atmosphere emits only blue light",
        "The sky reflects every ocean equally",
        "What redirects sunlight toward us from across the daytime sky?",
      ],
    ],
  ],
);
topic(
  "civics",
  "branches",
  "Power with limits",
  "How are federal powers divided?",
  "comparison",
  "United States federal government. A simplified constitutional introduction, not advice about a particular legal dispute.",
  [
    [
      "separated-powers",
      "Three branches, different jobs",
      "Congress legislates, the executive carries out laws, and federal courts interpret laws in cases before them.",
      "The branches have distinct roles and checks on one another.",
      "A presidential veto can block a bill, while Congress can override a veto with the required supermajorities. This is one check, not a complete account of constitutional powers.",
      "Legislative~Makes federal laws|Executive~Carries out laws|Judicial~Interprets laws in cases",
      "branches",
      "bill-law",
      [
        "Which federal branch includes Congress?",
        "Legislative",
        "Executive",
        "Judicial",
        "Which branch’s central job is making federal laws?",
      ],
    ],
    [
      "federalism",
      "National and state authority coexist",
      "Federalism divides authority between the national government and states.",
      "It is a different division from the three branches within the federal government.",
      "The Constitution gives specific powers to the national government and reserves other powers to states or the people. Some powers and responsibilities overlap.",
      "Federal~National constitutional powers|State~State governments and reserved powers|Shared~Some responsibilities overlap",
      "constitution",
      "separated-powers",
      [
        "Federalism concerns which division?",
        "National and state authority",
        "Courts and juries only",
        "Political parties only",
        "How does federalism differ from separation of the three federal branches?",
      ],
    ],
  ],
);
topic(
  "civics",
  "making-law",
  "From proposal to law",
  "Why is a bill not yet a law?",
  "flow",
  "Simplified US federal process. House and Senate procedures contain additional stages and exceptions.",
  [
    [
      "bill-law",
      "A bill has gates to pass",
      "A federal bill generally must pass both chambers in identical form and be presented to the president.",
      "Introducing a proposal does not make it law.",
      "The president can sign or veto a bill; Congress may override a veto. Constitutional rules also address unsigned bills and adjournment. The diagram shows the ordinary signed route.",
      "Proposal~A bill is introduced|Congress~Both chambers agree to the same text|President~Signs the bill into law",
      "laws",
      "term-limits",
      [
        "What must the House and Senate agree on before a bill is presented?",
        "Identical text",
        "Only its title",
        "Separate incompatible versions",
        "Two chambers pass different versions. What still needs to happen?",
      ],
    ],
    [
      "constitutional-change",
      "An amendment changes the Constitution",
      "Amending the US Constitution requires a proposal and ratification through the constitutional process.",
      "It is harder than passing an ordinary federal statute.",
      "The familiar route uses two-thirds of both houses to propose and three-fourths of states to ratify. Article V also provides a convention proposal route; the president does not sign amendments.",
      "Propose~For example, two-thirds of both houses|Ratify~Three-fourths of the states|Constitution~An amendment becomes part of it",
      "constitution",
      "term-limits",
      [
        "In the usual amendment route, what fraction of states must ratify?",
        "Three-fourths",
        "One-half",
        "All but one",
        "A proposed amendment needs how many states proportionally to ratify?",
      ],
    ],
  ],
);
topic(
  "civics",
  "representation",
  "Votes and representation",
  "What is being counted?",
  "comparison",
  "US federal institutions. Electoral rules vary by state; this overview does not provide current voting instructions.",
  [
    [
      "house-senate",
      "Population and equal state seats",
      "House representation is apportioned among states by population; each state has two senators.",
      "The chambers use different principles of representation.",
      "The House has 435 voting seats under current law. Population-based apportionment concerns distribution among states, not a direct national popular vote for every seat.",
      "House~Seats apportioned by population|Senate~Two senators per state|Congress~Both chambers participate in legislation",
      "constitution",
      "bill-law",
      [
        "Which chamber gives each state two seats?",
        "Senate",
        "House",
        "Supreme Court",
        "Which chamber gives small and large states the same number of members?",
      ],
    ],
    [
      "electoral-college",
      "The presidency uses electors",
      "The Electoral College is the constitutional mechanism for electing the president and vice president.",
      "Winning the national popular vote alone does not determine the electoral result.",
      "States receive electors based on their House and Senate representation; the District of Columbia receives electors under the Twenty-third Amendment. State allocation rules are not all identical.",
      "Voters~Vote under state electoral rules|Electors~Cast electoral votes|Count~A majority of electoral votes is required",
      "electoral",
      "presidency-1",
      [
        "What determines the ordinary presidential winner?",
        "A majority of electoral votes",
        "The number of states alone",
        "The national popular vote alone",
        "Why can the popular-vote leader differ from the presidential winner?",
      ],
    ],
  ],
);
topic(
  "finance",
  "growth",
  "Growth builds on growth",
  "What changes when interest earns interest?",
  "compound",
  "Hypothetical constant-rate annual compounding, with no fees, tax, contributions or guarantee of returns.",
  [
    [
      "compound-growth",
      "Interest can earn interest",
      "Compounding applies growth to both the initial amount and accumulated growth.",
      "Time changes the result even when the annual rate stays fixed.",
      "In the model, balance equals principal multiplied by (1 + rate) raised to the number of years. Real investment returns vary, and losses also compound.",
      "Start~An initial amount|Grow~Apply a rate to the balance|Repeat~The next period starts with the new balance",
      "compound",
      "percentage-points",
      [
        "With compound growth, the next period’s growth applies to what?",
        "The updated balance",
        "Only the original amount forever",
        "Only money withdrawn",
        "Why can yearly growth in dollars increase at a fixed percentage rate?",
      ],
    ],
    [
      "purchasing-power",
      "More dollars may buy less",
      "Purchasing power depends on both money amounts and prices.",
      "A nominal increase can coexist with a decline in what the money buys.",
      "If a balance rises 2% while the relevant prices rise 5%, its purchasing power falls. Personal spending patterns may differ from an aggregate inflation index.",
      "Money~Nominal amount changes|Prices~Cost of a basket changes|Real value~Compare the two changes",
      "inflation",
      "inflation-basket",
      [
        "Money rises 2% while relevant prices rise 5%. Purchasing power?",
        "Falls",
        "Rises by 7%",
        "Must stay constant",
        "Which direction does real buying power move in that example?",
      ],
    ],
  ],
);
topic(
  "finance",
  "borrowing",
  "The price of borrowing",
  "Why compare more than the headline rate?",
  "comparison",
  "General financial education using US terminology. Loan disclosures and costs depend on the product.",
  [
    [
      "interest-apr",
      "Rate and APR answer different questions",
      "For mortgages, APR includes the interest rate and certain additional loan charges.",
      "The lowest advertised rate need not identify the lowest overall borrowing cost.",
      "Compare like products and read the actual fees and terms. An APR is not a promise that every possible charge or future cost has been included.",
      "Interest rate~Charge for borrowing principal|Additional charges~Certain fees enter APR|APR~A broader annual cost measure",
      "apr",
      "compound-growth",
      [
        "Why can a mortgage APR exceed its interest rate?",
        "Certain loan fees are included",
        "APR ignores all fees",
        "APR is always a monthly rate",
        "Which measure includes certain loan charges in addition to interest?",
      ],
    ],
    [
      "credit-report",
      "A report is a record",
      "A credit report describes credit activity and account history supplied to a reporting company.",
      "A credit report and a credit score are different things.",
      "A score is a calculation using information such as that in a report. Reports can contain errors, so the accuracy of underlying records matters.",
      "Activity~Lenders report account information|Report~A record of credit history|Score~A calculated assessment using data",
      "credit",
      "data-backups",
      [
        "How does a credit report differ from a score?",
        "It is a record rather than a calculated number",
        "It predicts every future payment exactly",
        "It contains only income",
        "Which is the underlying account-history record?",
      ],
    ],
  ],
);
topic(
  "finance",
  "resilience",
  "Room for the unexpected",
  "What makes a financial plan more resilient?",
  "comparison",
  "General principles, not a recommendation for a particular allocation, product or emergency-fund amount.",
  [
    [
      "emergency-fund",
      "A buffer has a job",
      "An emergency fund is money set aside for unplanned financial needs.",
      "Accessible savings can reduce reliance on borrowing during a shock.",
      "The useful amount depends on circumstances. The key distinction is between a reserve intended for unexpected costs and money already committed to known bills.",
      "Known costs~Plan for recurring bills|Unexpected costs~A reserve can absorb shocks|Access~Money must be available when needed",
      "emergency",
      "opportunity-cost",
      [
        "What is an emergency fund primarily for?",
        "Unplanned financial needs",
        "Guaranteeing investment profits",
        "Replacing every regular bill forever",
        "What distinguishes emergency savings from money budgeted for rent?",
      ],
    ],
    [
      "diversification",
      "Avoid one point of financial failure",
      "Diversification spreads investments across holdings to reduce concentration risk.",
      "It cannot guarantee profits or prevent every loss.",
      "Owning several funds does not necessarily create broad diversification if they hold the same assets. The underlying exposures matter more than the count of account names.",
      "Concentrated~One exposure dominates|Distributed~Different holdings share exposure|Remaining risk~Markets can still fall together",
      "diversify",
      "independent-events",
      [
        "What can diversification do?",
        "Reduce concentration risk",
        "Guarantee a positive return",
        "Eliminate all market risk",
        "Why look at overlapping holdings when comparing funds?",
      ],
    ],
  ],
);
topic(
  "tech",
  "internet",
  "A request crosses a network",
  "What happens when you open a web page?",
  "flow",
  "Simplified request sequence. Caches, connections and modern protocols can alter the exact steps.",
  [
    [
      "dns-routing",
      "Names and addresses do different jobs",
      "DNS helps translate a domain name into network addressing information.",
      "A memorable name does not itself tell a network where to send every packet.",
      "Networks route packets between devices. DNS resolution and packet routing are related parts of the journey, but they are not the same operation.",
      "Name~A human-readable domain|DNS~Find addressing information|Network~Route packets toward a destination",
      "network,web",
      "phishing-links",
      [
        "What is DNS’s role?",
        "Resolve names to addressing information",
        "Write every page’s content",
        "Guarantee a site is honest",
        "A browser has a domain name and needs an address. Which system helps?",
      ],
    ],
    [
      "https-trust",
      "An encrypted connection is not an endorsement",
      "HTTPS protects data in transit between a browser and its connected site.",
      "An encrypted connection alone does not prove the site’s claims or intentions are trustworthy.",
      "A deceptive site can also use HTTPS. Verify the actual domain and the context of a request, especially before entering sensitive information.",
      "Browser~Connects to a named site|Encryption~Protects the connection in transit|Judgment~Still evaluate the site and request",
      "web",
      "phishing-links",
      [
        "What does HTTPS alone fail to guarantee?",
        "That the site’s operator is honest",
        "That a connection uses encryption",
        "That data travels over a network",
        "A fraudulent page uses HTTPS. What should you conclude?",
      ],
    ],
  ],
);
topic(
  "tech",
  "instructions",
  "Small instructions, large effects",
  "How does a computer follow a method?",
  "flow",
  "Teaching examples of algorithms; these steps are not a claim about the implementation of every search engine.",
  [
    [
      "algorithm-steps",
      "An algorithm is a method",
      "An algorithm is a sequence of steps for solving a problem or performing a task.",
      "A method needs specified inputs, decisions and a way to finish.",
      "To find a name in a short list, inspect each entry until a match appears or the list ends. The stopping rule prevents an endless search when there is no match.",
      "Input~A list and a target|Steps~Compare entries in order|Stop~Return a match or report none",
      "algorithm",
      "ai-training",
      [
        "Why does a search need a stopping rule?",
        "The target might be absent",
        "Every target is always first",
        "Computers never repeat steps",
        "What should a list-search method do after checking every entry without a match?",
      ],
    ],
    [
      "binary-search",
      "Halving needs order",
      "Binary search repeatedly narrows a sorted search range by comparing its middle item.",
      "Its speed relies on the data being ordered appropriately.",
      "If the target precedes the middle item, discard the later half; otherwise discard the earlier half when appropriate. On an unsorted list, those eliminations are not justified.",
      "Sort order~Makes comparisons meaningful|Middle~Compare with the target|Half~Keep only the possible side",
      "algorithm",
      "sampling-bias",
      [
        "What condition does ordinary binary search need?",
        "A sorted collection",
        "All entries identical",
        "An Internet connection",
        "Why can halving an unsorted list discard the target?",
      ],
    ],
  ],
);
topic(
  "tech",
  "data",
  "Where your data lives",
  "Does saving mean it is backed up?",
  "comparison",
  "Storage behavior varies by browser and service. This site stores locally and provides an explicit downloadable backup.",
  [
    [
      "local-cloud",
      "Local and remote storage have different boundaries",
      "Browser storage belongs to an origin and browser profile; remote services store data on other systems.",
      "A local save does not automatically synchronize to another device.",
      "Clearing site data or using another browser profile can change what is available. A cloud service may synchronize selected data, depending on its design and your account settings.",
      "Local~This browser and origin|Remote~Another system or service|Sync~An explicit transfer mechanism",
      "storage",
      "data-backups",
      [
        "Why might saved browser data be absent in another browser?",
        "Local storage is scoped to a browser profile and origin",
        "Every save is automatically global",
        "Data can only exist on paper",
        "What does a local save alone fail to provide?",
      ],
    ],
    [
      "data-backups",
      "Recovery needs another usable copy",
      "A backup is a recoverable copy kept for restoring data after loss or damage.",
      "A copy that cannot be opened or restored is not a proven recovery path.",
      "For this site, export a JSON backup and use the import preview to inspect it before importing. Keeping a copy separately protects against loss of this browser’s local data.",
      "Create~Export a copy|Separate~Keep it beyond the original failure point|Restore~Check that recovery works",
      "storage",
      "device-updates",
      [
        "Which makes a backup useful?",
        "A copy that can actually be restored",
        "A filename with no data",
        "Only an unsaved browser tab",
        "What should be checked in addition to making a backup file?",
      ],
    ],
  ],
);
topic(
  "health",
  "infection",
  "Defenses and treatments",
  "Why are vaccines and antibiotics different?",
  "comparison",
  "General health education. Specific treatment decisions depend on the person, infection and clinical assessment.",
  [
    [
      "vaccines",
      "Vaccines prepare immune defenses",
      "Vaccines train immune responses against particular infections without requiring the full disease experience.",
      "Prevention and treatment are different goals.",
      "Protection varies by vaccine and can change over time. Vaccination does not mean every exposure becomes impossible or that every illness has a vaccine.",
      "Prepare~Introduce a safe immune training signal|Respond~Immune defenses develop|Encounter~Later responses can be better prepared",
      "vaccine",
      "antibiotic-limits",
      [
        "What is vaccination primarily intended to do?",
        "Prepare protection against a target infection",
        "Treat every bacterial infection immediately",
        "Eliminate all future illness",
        "How does a vaccine’s main role differ from treating an existing infection?",
      ],
    ],
    [
      "antibiotic-limits",
      "Antibiotics target bacteria, not viruses",
      "Antibiotics treat certain bacterial infections; they do not treat viral infections such as colds.",
      "Using an antibiotic for the wrong kind of infection does not create the intended benefit.",
      "Antibiotic use can cause side effects and contributes to resistance pressure. Whether one is needed depends on the diagnosis rather than symptoms alone.",
      "Bacteria~Some infections respond to antibiotics|Viruses~Antibiotics do not target them|Assessment~Determine the cause and appropriate care",
      "antibiotics",
      "vaccines",
      [
        "Why do antibiotics not treat a viral cold?",
        "They do not target viruses",
        "All infections are identical",
        "They are the same as vaccines",
        "Which infection category is outside antibiotics’ target?",
      ],
    ],
  ],
);
topic(
  "health",
  "body",
  "Systems and quantities",
  "What flows, and what is a serving?",
  "cycle",
  "Simplified circulation and label-reading examples. Food labels are not individualized dietary prescriptions.",
  [
    [
      "circulation",
      "The heart connects two circuits",
      "The right side of the heart sends blood to the lungs; the left sends oxygen-rich blood to the body.",
      "The lung and body circuits connect in a continuous flow.",
      "Arteries carry blood away from the heart and veins carry it toward the heart. Those directions are more reliable definitions than “arteries always carry oxygen-rich blood.”",
      "Right heart~Sends blood to lungs|Lungs~Gas exchange occurs|Left heart → body~Delivers oxygen-rich blood to tissues",
      "heart",
      "sound-medium",
      [
        "Which side sends blood toward the lungs?",
        "Right side",
        "Left side",
        "Neither side",
        "Where does blood leaving the right side of the heart go next?",
      ],
    ],
    [
      "serving-size",
      "The label’s quantity matters",
      "Nutrition Facts values are stated for a defined serving, which may differ from the amount you eat.",
      "Two servings generally mean twice the listed amount of a nutrient or calories.",
      "A serving size reflects amounts people typically consume; it is not a recommendation for how much you personally should eat. Check the number of servings in a package.",
      "Per serving~A stated reference amount|Amount eaten~May be one or several servings|Total~Scale values to the amount consumed",
      "nutrition",
      "percentage-points",
      [
        "A label lists 100 calories per serving; you eat two. Total?",
        "200 calories",
        "100 calories",
        "50 calories",
        "How should per-serving quantities change for two servings?",
      ],
    ],
  ],
);
topic(
  "health",
  "health-evidence",
  "A result needs context",
  "What does a test result actually mean?",
  "comparison",
  "Illustrative diagnostic reasoning, not a diagnosis. Consult the laboratory explanation and a clinician for personal results.",
  [
    [
      "test-results",
      "A result is one piece of evidence",
      "Medical test results are interpreted alongside symptoms, history and other information.",
      "An abnormal result does not by itself establish a diagnosis.",
      "Reference ranges depend on the test and laboratory. A result inside a range does not always rule out illness, and a result outside it does not always mean illness.",
      "Result~A measured or classified finding|Context~History, symptoms and test limitations|Interpretation~Combine evidence, sometimes with further testing",
      "testing",
      "base-rates",
      [
        "Why is one abnormal test not always a diagnosis?",
        "Results require clinical context and interpretation",
        "Tests are never useful",
        "Reference ranges never vary",
        "What else can matter besides whether a result is flagged?",
      ],
    ],
    [
      "screening-errors",
      "Tests can be wrong in two directions",
      "A false positive flags a condition that is absent; a false negative misses one that is present.",
      "The chance a positive result reflects disease also depends on how common the condition is in the tested group.",
      "The accompanying numbers lesson uses an invented test and population. It illustrates base rates, not the accuracy of any particular medical product.",
      "False positive~Condition absent, test positive|False negative~Condition present, test negative|Base rate~How common the condition is before testing",
      "testing",
      "base-rates",
      [
        "A test is positive but the condition is absent. What is this?",
        "False positive",
        "False negative",
        "True negative",
        "Which error incorrectly flags a condition?",
      ],
    ],
  ],
);
topic(
  "economics",
  "production",
  "Count what gets made",
  "What does GDP include?",
  "flow",
  "Introductory national accounting. GDP is not a complete measure of welfare or all useful activity.",
  [
    [
      "gdp-output",
      "GDP counts domestic production",
      "GDP measures the value of final goods and services produced within a country during a period.",
      "“Domestic” concerns where production occurs.",
      "Final-output accounting avoids repeatedly counting intermediate inputs. GDP is useful for production comparisons but does not directly summarize distribution, unpaid work or environmental quality.",
      "Production~Goods and services produced|Boundary~Within a country and a period|Final value~Avoid repeated intermediate counting",
      "gdp",
      "purchasing-power",
      [
        "GDP is primarily a measure of what?",
        "Domestic production in a period",
        "Every citizen’s happiness",
        "The stock of all wealth ever created",
        "What does the “domestic” boundary in GDP refer to?",
      ],
    ],
    [
      "value-added",
      "Do not count the flour twice",
      "Value added at a stage is output value minus the intermediate inputs bought from other producers.",
      "Adding each stage’s contribution avoids double counting.",
      "Illustration: flour sold for $2 is used in bread sold for $5. Counting both sales as final output gives $7, but the bread’s final value is $5; the baker added $3.",
      "Flour~$2 intermediate input|Baker~Adds $3 of value|Bread~$5 final output",
      "gdp",
      "algorithm-steps",
      [
        "Flour costs $2; finished bread sells for $5. Baker’s value added?",
        "$3",
        "$7",
        "$5",
        "How much additional value did the baker contribute in that example?",
      ],
    ],
  ],
);
topic(
  "economics",
  "prices",
  "Prices send signals",
  "How do demand and broad inflation differ?",
  "market",
  "Supply and demand curves are illustrative, with other factors held constant. They are not a market forecast.",
  [
    [
      "supply-demand",
      "A price change is not a curve shift",
      "A product’s own price changes the quantity demanded along a given demand curve; other factors can shift the curve.",
      "Distinguish a movement along a relationship from a change in that relationship.",
      "In a simplified market, higher willingness to buy at every price shifts demand outward. With upward-sloping supply and other things equal, equilibrium price and quantity rise.",
      "Demand~Quantities buyers want at different prices|Supply~Quantities sellers offer at different prices|Intersection~A simplified market balance",
      "demand,supply",
      "opportunity-cost",
      [
        "More willingness to buy at every price represents what?",
        "A demand-curve shift",
        "Only movement along unchanged demand",
        "The disappearance of scarcity",
        "If preferences increase demand at every price, what changed?",
      ],
    ],
    [
      "inflation-basket",
      "Inflation is broader than one price",
      "The CPI tracks average price change for a basket of consumer goods and services paid for by urban consumers.",
      "A single item becoming expensive is not the same as an aggregate inflation rate.",
      "The basket and weights summarize spending across consumers. Your own experience can differ when your purchases and their proportions differ from the index.",
      "Items~Many prices change differently|Weights~Spending shares affect the index|Index~An aggregate measure over time",
      "inflation",
      "purchasing-power",
      [
        "Why might your costs rise differently from CPI?",
        "Your spending mix differs from the basket",
        "CPI measures only one product",
        "Every household buys identical quantities",
        "What connects a personal inflation experience to an aggregate index?",
      ],
    ],
  ],
);
topic(
  "economics",
  "choices",
  "Every yes has a cost",
  "What do you give up when you choose?",
  "comparison",
  "Illustrative choices, not personalized financial or career advice.",
  [
    [
      "opportunity-cost",
      "The next-best alternative matters",
      "Opportunity cost is the value of the next-best alternative forgone when choosing.",
      "It includes alternatives involving time, not just cash payments.",
      "If an hour can be used for either studying or paid work, choosing study forgoes that work opportunity. Do not add together every incompatible alternative as though all could have happened.",
      "Choice~Use a scarce resource|Alternative~Identify the next-best feasible use|Cost~Value what was forgone",
      "scarcity",
      "emergency-fund",
      [
        "Opportunity cost is the value of what?",
        "The next-best alternative forgone",
        "Every possible alternative added together",
        "Only the cash receipt",
        "An hour of study replaces an hour of available work. What was forgone?",
      ],
    ],
    [
      "sunk-cost",
      "Past costs cannot be recovered by wishing",
      "A sunk cost has already been incurred and cannot be recovered by the current choice.",
      "Compare future benefits and costs when deciding what to do next.",
      "Illustration: a nonrefundable ticket is already paid for. Whether to attend still depends on what attending now offers and costs, including time; going cannot undo the earlier payment.",
      "Past~An unrecoverable payment|Now~Available choices remain|Future~Compare consequences of those choices",
      "scarcity",
      "correlation",
      [
        "A nonrefundable payment already made is what kind of cost?",
        "Sunk cost",
        "A guaranteed future benefit",
        "A refundable deposit",
        "Can attending solely to justify a past nonrefundable ticket recover the payment?",
      ],
    ],
  ],
);
topic(
  "ai",
  "learning-models",
  "Learning from examples",
  "When does a pattern generalize?",
  "flow",
  "Simplified supervised-learning workflow. Real model architectures and training methods vary.",
  [
    [
      "ai-training",
      "Training changes a model",
      "Training uses examples and an objective to adjust a model’s parameters.",
      "Testing on new data asks a different question from fitting the training examples.",
      "A model can exploit patterns that were useful in training but do not hold elsewhere. Separate evaluation data helps reveal that gap when it represents the intended use.",
      "Examples~Training data and targets|Adjustment~Optimize parameters against an objective|Evaluation~Check performance on unseen examples",
      "training",
      "sampling-bias",
      [
        "Why evaluate on unseen examples?",
        "To test generalization beyond training data",
        "To guarantee perfection everywhere",
        "To replace all training data with answers",
        "What does a separate evaluation set help check?",
      ],
    ],
    [
      "overfitting",
      "Memorizing the pattern is not enough",
      "Overfitting occurs when a model performs well on training data but poorly on new examples.",
      "Training success alone is weak evidence of dependable use elsewhere.",
      "Model complexity, limited data or unrepresentative examples can contribute. Validation checks should match the expected task, while keeping the final evaluation separate from repeated tuning.",
      "Training~Very good fit|New examples~Performance deteriorates|Diagnosis~The learned pattern did not generalize",
      "training",
      "correlation",
      [
        "Excellent training results but poor unseen results suggest what?",
        "Overfitting",
        "Guaranteed generalization",
        "Perfect calibration",
        "What can be wrong even when training accuracy is high?",
      ],
    ],
  ],
);
topic(
  "ai",
  "generation",
  "Plausible is not verified",
  "How does generated text earn trust?",
  "flow",
  "Introductory account of language generation. Some systems add retrieval or tools; their output still needs evaluation.",
  [
    [
      "generated-text",
      "Generation builds a continuation",
      "A language model generates text using learned patterns to predict continuations represented as tokens.",
      "Producing fluent text does not establish that its claims are true.",
      "The system may use additional retrieved information or tools, but a polished sentence is still not its own evidence. Check important claims against appropriate sources.",
      "Context~Instructions and available material|Prediction~Generate token continuations|Output~Fluent text that needs checking",
      "genai",
      "source-verification",
      [
        "What does fluent model output establish by itself?",
        "That the text is fluent, not that every claim is true",
        "That every cited source exists",
        "That all facts were checked live",
        "Why is confident wording insufficient evidence of correctness?",
      ],
    ],
    [
      "confabulation",
      "A model can invent a convincing detail",
      "Generative AI can produce false or unsupported content, including plausible citations.",
      "A citation must be checked for existence and support.",
      "Open the source and confirm that it actually substantiates the claim. A real publication with a related title may still not support the specific assertion being made.",
      "Claim~Sounds specific|Citation~May be real, wrong or invented|Check~Confirm existence and relevant support",
      "genai",
      "source-verification",
      [
        "What should you check about an AI-provided citation?",
        "That it exists and supports the specific claim",
        "Only that it looks academic",
        "Only that the URL is long",
        "A cited article exists. What must still be checked?",
      ],
    ],
  ],
);
topic(
  "ai",
  "judgment",
  "Put judgment around the model",
  "Who is missing, and what is supported?",
  "comparison",
  "Risk depends on context and affected people. A single performance number does not settle suitability.",
  [
    [
      "model-bias",
      "Bias enters at several points",
      "AI bias can arise through data, design choices and the social context in which a system is used.",
      "One overall accuracy number can hide uneven performance across groups.",
      "Ask whose examples were included, what the objective rewards, and who bears the errors. Evaluation should consider relevant groups and conditions rather than assuming average performance applies to everyone.",
      "Data~Who and what is represented|Design~What the objective rewards|Use~Who experiences the consequences",
      "bias",
      "sampling-bias",
      [
        "Why inspect performance beyond one overall average?",
        "It can hide uneven errors across groups",
        "An average lists every individual error",
        "All groups must perform identically",
        "What can a single accuracy number conceal?",
      ],
    ],
    [
      "source-verification",
      "Trace a claim to evidence",
      "Verification checks whether reliable evidence supports the particular claim, with the needed date and context.",
      "Finding a related page is not enough.",
      "Use the original data, official documentation or relevant primary work when possible. Separate an observed result from an extrapolation, and distinguish what was checked from what remains uncertain.",
      "Claim~State precisely what is asserted|Evidence~Inspect an appropriate source|Scope~Check date, conditions and limitations",
      "genai",
      "correlation",
      [
        "Which is a stronger verification step?",
        "Check that the source supports the precise claim",
        "Count how many times a claim is repeated",
        "Accept a polished summary without opening its source",
        "What should you compare with a source’s actual contents?",
      ],
    ],
  ],
);
topic(
  "cyber",
  "identity",
  "Protect the way in",
  "What happens if one password escapes?",
  "comparison",
  "General protective habits. No single measure prevents every account attack.",
  [
    [
      "unique-passwords",
      "Reused secrets connect failures",
      "A different strong password for each account limits the damage when one credential is exposed.",
      "Password reuse lets one compromise become a route into other accounts.",
      "A password manager can help generate and keep unique passwords. Protect the manager itself carefully and follow its recovery guidance.",
      "Reuse~One secret opens several doors|Exposure~An attacker learns that secret|Unique passwords~Other accounts use different secrets",
      "passwords",
      "multifactor",
      [
        "Why avoid reusing a password across accounts?",
        "One exposed secret could unlock several accounts",
        "Every website shares the same security settings",
        "Long passwords cannot be exposed",
        "What limits the spread of a stolen password to other accounts?",
      ],
    ],
    [
      "multifactor",
      "Add another kind of proof",
      "Multifactor authentication requires more than one category of authentication evidence.",
      "A stolen password alone is less useful when another factor is required.",
      "Methods differ in resistance to phishing. Follow trusted setup instructions and preserve recovery options; adding a factor is not a reason to approve an unexpected login request.",
      "Know~A password or PIN|Have or are~A device or biometric factor|Verify~Require the configured factors",
      "mfa",
      "phishing-links",
      [
        "Which best describes multifactor authentication?",
        "More than one category of proof",
        "The same password typed twice",
        "Two security questions only",
        "Why can an extra factor help after a password is stolen?",
      ],
    ],
  ],
);
topic(
  "cyber",
  "deception",
  "Pause at the request",
  "What is this message asking you to do?",
  "flow",
  "Illustrative defensive inspection. No real credential forms, executable attachments or malicious links are included.",
  [
    [
      "phishing-links",
      "Urgency is a reason to verify",
      "Phishing messages try to induce actions such as revealing information or opening unsafe links.",
      "Verify a surprising request through an independently chosen trusted channel.",
      "Do not use a phone number or link from the suspicious message as the only verification route. Open the known service yourself or use contact information obtained independently.",
      "Message~An urgent or unexpected request|Pause~Inspect the sender and requested action|Verify~Use an independent trusted route",
      "phishing",
      "https-trust",
      [
        "An unexpected urgent message asks for your password. Best next step?",
        "Verify independently through the known service",
        "Reply with the password quickly",
        "Trust it because it has a logo",
        "Which verification route avoids relying on the suspicious message itself?",
      ],
    ],
    [
      "domain-names",
      "Read the actual destination",
      "A link’s displayed text can differ from its destination, and lookalike names can imitate trusted services.",
      "A familiar word somewhere in a URL does not establish ownership.",
      "In https://accounts.example.com, example.com is the example registered domain. In https://example.com.attacker.invalid, the example.com text is only a subdomain of attacker.invalid. These are nonfunctional teaching examples.",
      "Display text~Can say anything|Destination~Inspect the actual host|Context~Verify the request independently",
      "phishing",
      "dns-routing",
      [
        "Does a familiar brand word anywhere in a URL prove ownership?",
        "No",
        "Yes, always",
        "Only if it is at the beginning",
        "Why inspect the actual hostname instead of just link text?",
      ],
    ],
  ],
);
topic(
  "cyber",
  "recovery",
  "Close gaps, keep a way back",
  "How do maintenance and recovery work together?",
  "flow",
  "General device hygiene; exact update and recovery steps depend on the device and vendor.",
  [
    [
      "device-updates",
      "Updates can close known weaknesses",
      "Software updates often include fixes for security vulnerabilities as well as other changes.",
      "Delaying a security fix can leave a known weakness available to attackers.",
      "Use trusted built-in update mechanisms or the vendor’s official source. A surprise message claiming an urgent update may itself be deceptive.",
      "Weakness~A vulnerability is discovered|Fix~The vendor issues an update|Install~Apply it through a trusted mechanism",
      "updates",
      "data-backups",
      [
        "Why do security updates matter?",
        "They can fix known vulnerabilities",
        "They make backups unnecessary",
        "They prove every message is safe",
        "What can remain exposed when a security fix is repeatedly postponed?",
      ],
    ],
    [
      "recovery-plan",
      "Practice the route back",
      "Account recovery and data restoration are easier when the needed information and copies already exist.",
      "Recovery preparation complements prevention.",
      "Keep recovery options current using the service’s trusted settings and keep usable backups separately. Do not share recovery codes with an unexpected caller or message.",
      "Prepare~Save recovery options safely|Separate~Keep usable backup copies|Restore~Check the recovery process",
      "mfa,storage",
      "data-backups",
      [
        "Why prepare recovery before a failure?",
        "Needed copies and options may be unavailable afterward",
        "It prevents all attacks permanently",
        "It replaces every password",
        "What makes a restore possible after losing the original device?",
      ],
    ],
  ],
);
topic(
  "numbers",
  "percentages",
  "Percent of what?",
  "How can two true percentages tell different stories?",
  "percent",
  "Invented arithmetic examples, not observed rates for any treatment or population.",
  [
    [
      "percentage-points",
      "A difference between percentages has units",
      "A change from 10% to 15% is 5 percentage points, or a 50% increase relative to the starting rate.",
      "The absolute difference and relative change answer different questions.",
      "Relative change divides the difference by the starting value: (15 − 10) / 10 = 0.5. Always identify the starting value; relative change from zero is not defined by that formula.",
      "Start~10 out of 100|End~15 out of 100|Difference~5 points; 50% of the starting rate",
      "percentages",
      "efficiency",
      [
        "A rate rises from 10% to 15%. Absolute difference?",
        "5 percentage points",
        "50 percentage points",
        "5% relative increase",
        "Subtracting 10% from 15% gives what difference in percentage points?",
      ],
    ],
    [
      "absolute-relative",
      "Ask for the baseline",
      "A reduction from 2 in 100 to 1 in 100 is a 50% relative reduction and a 1 percentage-point absolute reduction.",
      "The relative number alone hides how common the outcome was initially.",
      "Neither expression is inherently false. A useful explanation gives the baseline, resulting rate and population or time period, so the practical size can be understood.",
      "Before~2 in 100|After~1 in 100|Both true~50% relative; 1 point absolute",
      "percentages",
      "screening-errors",
      [
        "A rate falls from 2% to 1%. Relative reduction?",
        "50%",
        "1%",
        "100%",
        "What fraction of the original 2% rate was removed?",
      ],
    ],
  ],
);
topic(
  "numbers",
  "chance",
  "Chance has conditions",
  "When do probabilities multiply?",
  "probability",
  "Invented fair-coin and test examples. They illustrate assumptions rather than predict personal outcomes.",
  [
    [
      "independent-events",
      "Independence is an assumption",
      "Independent events do not change one another’s probabilities.",
      "For independent events, multiply probabilities to find the chance that both occur.",
      "For two independent fair coin tosses, the chance of two heads is 1/2 × 1/2 = 1/4. A previous run of heads does not make the next independent toss “due” to be tails.",
      "First toss~Heads has probability 1/2|Second toss~Still 1/2 if independent|Both heads~1/4 of the four equal outcomes",
      "probability",
      "diversification",
      [
        "Two independent fair tosses: chance of two heads?",
        "1/4",
        "1/2",
        "1",
        "Before either fair independent toss, what is the chance the pair will be HH?",
      ],
    ],
    [
      "base-rates",
      "Rare conditions change the meaning of a positive",
      "The share of positive tests that are true positives depends on prevalence as well as the test’s error rates.",
      "Even a small false-positive rate can produce many false positives in a mostly unaffected population.",
      "Invented example: of 1,000 people, 10 have a condition. A test finds 9 of those and incorrectly flags 99 of the other 990. Only 9 of 108 positives are true positives, about 8.3%.",
      "Condition present~10 people; 9 test positive|Condition absent~990 people; 99 test positive|All positives~9 true out of 108 total",
      "testing,probability",
      "screening-errors",
      [
        "In the invented example, how many positive tests are true positives?",
        "9 of 108",
        "99 of 108",
        "9 of 10 total positives",
        "Why are most positives false in this invented rare-condition example?",
      ],
    ],
  ],
);
topic(
  "numbers",
  "evidence",
  "A pattern is a starting point",
  "Who was sampled, and what caused what?",
  "comparison",
  "Illustrative reasoning. Correlation can motivate investigation but does not by itself establish a causal effect.",
  [
    [
      "sampling-bias",
      "A large sample can still miss people",
      "A sample supports inferences about a population only to the extent that its design and collection are suitable.",
      "More responses do not automatically fix a systematically biased selection process.",
      "A voluntary website poll can overrepresent people who visit the site and choose to respond. Ask who could be included, who actually responded and how that relates to the target population.",
      "Population~Whom the claim concerns|Selection~Who had a chance to participate|Sample~Who was actually measured",
      "sampling",
      "model-bias",
      [
        "Can a very large voluntary poll still be biased?",
        "Yes, selection can remain unrepresentative",
        "No, size removes every bias",
        "Only if exactly ten people answer",
        "Why ask who was excluded even when a poll has many responses?",
      ],
    ],
    [
      "correlation",
      "Moving together does not prove a cause",
      "Correlation describes a statistical relationship; it does not by itself establish that one variable causes another.",
      "A third factor, reverse causation or other explanations may account for a pattern.",
      "Illustration: hot weather can increase both ice-cream sales and swimming. A relationship between the two activities does not show that buying ice cream causes swimming.",
      "Observed~Two variables move together|Alternatives~A third cause or reversed direction|Investigation~Use a suitable design to test explanations",
      "causation",
      "source-verification",
      [
        "Two variables move together. What follows immediately?",
        "There is a relationship to investigate",
        "One must cause the other",
        "No other factor can matter",
        "What does a correlation alone fail to establish?",
      ],
    ],
  ],
);
// Application variants are independently worded and contain their own context.
const applications = {
  "tectonic-plates": [
    "Two plates slide sideways alongside each other. What kind of boundary is this?",
    "Transform",
    "Divergent",
    "Convergent",
  ],
  "energy-transfer": [
    "Brakes warm as a bicycle slows. Which explanation fits conservation of energy?",
    "Motion energy transfers into heat and other forms",
    "The brakes destroy the energy",
    "No energy changes form",
  ],
  efficiency: [
    "A device receives 200 J and delivers 60 J of useful output. What is its efficiency?",
    "30%",
    "60%",
    "70%",
  ],
  "dna-information": [
    "What can make two DNA segments carry different information?",
    "A different sequence of bases",
    "Only a different total cell size",
    "Only their distance from the Sun",
  ],
  "sound-medium": [
    "Why can ordinary sound not cross a vacuum?",
    "There is no matter to transmit the vibrations",
    "Sound requires blue light",
    "Vacuum makes every wave travel faster",
  ],
  federalism: [
    "A question concerns authority shared between a US state and the national government. Which idea is relevant?",
    "Federalism",
    "Only separation of the three federal branches",
    "Only the number of senators",
  ],
  "bill-law": [
    "The House and Senate pass different versions of a bill. What must happen before presentation to the president?",
    "They must agree to identical text",
    "The titles alone must match",
    "One chamber can erase the other’s vote",
  ],
  "electoral-college": [
    "A candidate wins the national popular vote but not an electoral-vote majority. Why is popular support alone insufficient?",
    "The constitutional election mechanism uses electoral votes",
    "Only the largest state votes",
    "Congress counts only Senate seats",
  ],
  "compound-growth": [
    "An account earns 5% on $1,000, then 5% on $1,050. Why is the second dollar gain larger?",
    "The percentage applies to a larger balance",
    "The stated percentage doubled",
    "The initial amount was withdrawn",
  ],
  "purchasing-power": [
    "A balance grows 2% while the prices relevant to its owner grow 5%. What happens to purchasing power?",
    "It falls",
    "It rises by 7%",
    "It must stay unchanged",
  ],
  "interest-apr": [
    "Two mortgages have the same stated interest rate but different included fees. Which broader measure helps compare these costs?",
    "APR",
    "Only the interest rate",
    "The street address of the lender",
  ],
  "credit-report": [
    "You find an incorrect account entry in your credit history. Which underlying record contains that information?",
    "A credit report",
    "Only a credit score",
    "The Consumer Price Index",
  ],
  diversification: [
    "Two funds mostly hold the same stocks. Why might owning both provide less diversification than expected?",
    "Their underlying exposures overlap",
    "More account names always eliminate risk",
    "Every fund guarantees profits",
  ],
  "dns-routing": [
    "A browser has a domain name and needs network addressing information. Which system helps?",
    "DNS",
    "A nutrition label",
    "A password hint",
  ],
  "https-trust": [
    "A deceptive website uses HTTPS. What follows?",
    "Encryption alone does not establish the operator’s honesty",
    "The operator must be trustworthy",
    "The website cannot request sensitive information",
  ],
  "algorithm-steps": [
    "A search checks every list entry without finding the target. What should a complete method do?",
    "Stop and report no match",
    "Continue checking forever",
    "Claim the last entry is a match",
  ],
  "binary-search": [
    "Why is discarding half an unsorted list after one middle comparison unsafe?",
    "The target may be in the discarded half",
    "Unsorted lists cannot contain values",
    "A middle item always proves the target absent",
  ],
  "local-cloud": [
    "You save a note in one browser’s local storage. What has that action alone not established?",
    "That the note is synchronized to another device",
    "That the browser can hold data",
    "That the save happened on a particular origin",
  ],
  "data-backups": [
    "You downloaded a backup but have never opened or restored it. What remains unproven?",
    "That the copy can support recovery",
    "That the filename exists",
    "That your original data is currently readable",
  ],
  "antibiotic-limits": [
    "A patient has an infection caused by a virus. Why are antibiotics not a treatment for that virus?",
    "Antibiotics do not target viruses",
    "Viruses are the same as bacteria",
    "Every infection requires an antibiotic",
  ],
  circulation: [
    "Where does blood leaving the right side of the heart go?",
    "Toward the lungs",
    "Directly into the left ventricle without passing the lungs",
    "First to every body tissue",
  ],
  "serving-size": [
    "A package lists 100 calories per serving and contains three servings. What is the total if all of it is eaten?",
    "300 calories",
    "100 calories",
    "33 calories",
  ],
  "test-results": [
    "A result falls outside a laboratory reference range. What is the next interpretive principle?",
    "Combine it with clinical context and test limitations",
    "Treat it as a complete diagnosis by itself",
    "Ignore every abnormal result",
  ],
  "gdp-output": [
    "A factory produces final goods within a country this year. Which boundary makes that production domestic for GDP?",
    "Where the production occurs",
    "The nationality of every customer",
    "The owner’s favorite currency",
  ],
  "value-added": [
    "A baker buys $3 of intermediate ingredients and sells the bread for $8. What value did the baker add?",
    "$5",
    "$11",
    "$8",
  ],
  "inflation-basket": [
    "A person spends far more on rent than the average basket weight. Why might their experienced inflation differ from CPI?",
    "Their spending proportions differ",
    "The CPI is only a rent index",
    "Every individual must match the average",
  ],
  "opportunity-cost": [
    "You choose an hour of study instead of an available hour of paid work, your next-best option. What is the opportunity cost?",
    "The value of that forgone work opportunity",
    "Every imaginable use of the hour added together",
    "Only the price of a pencil",
  ],
  "sunk-cost": [
    "A ticket is nonrefundable and already paid for. Which consideration should guide whether to attend now?",
    "Future benefits and costs of attending versus alternatives",
    "The hope that attending will reverse the past payment",
    "The price of every ticket you have ever bought",
  ],
  "ai-training": [
    "A model is evaluated on examples kept out of training. What does this help assess?",
    "Generalization to unseen examples",
    "Whether every future use is guaranteed safe",
    "Whether training is no longer needed",
  ],
  "generated-text": [
    "A model states a claim confidently but supplies no checked evidence. What should be inferred?",
    "Confidence of wording is not verification of truth",
    "The claim was certainly checked against live records",
    "Fluency prevents factual errors",
  ],
  confabulation: [
    "An AI citation links to a real article. What still needs checking?",
    "Whether the article supports the specific claim",
    "Only whether the link is blue",
    "Nothing; any real article proves the claim",
  ],
  "model-bias": [
    "A model has high average accuracy but performs poorly for one relevant group. What did the average hide?",
    "Uneven performance across groups",
    "A guarantee that every user gets the same result",
    "The complete list of individual errors",
  ],
  "source-verification": [
    "A source discusses the same subject as a claim. What is still needed to verify the claim?",
    "Confirm support for its precise assertion and context",
    "Only count the page’s words",
    "Assume topical similarity is sufficient",
  ],
  "unique-passwords": [
    "One service exposes your password. What limits that exact password from opening your other accounts?",
    "Using different passwords on those accounts",
    "Reusing it with the same username everywhere",
    "Adding the same password hint everywhere",
  ],
  multifactor: [
    "An attacker learns a password. How can configured MFA add protection?",
    "It requires another category of authentication evidence",
    "It makes the stolen password unknown again",
    "It guarantees that recovery information is never needed",
  ],
  "domain-names": [
    "Why can link text reading “Your bank” be misleading?",
    "Displayed text can differ from the destination",
    "Displayed text always proves ownership",
    "Every link with a familiar word is safe",
  ],
  "device-updates": [
    "A vendor fixes a known security vulnerability, but a device never installs the fix. What risk remains?",
    "The known weakness may still be exploitable",
    "The update automatically installs by being announced",
    "All backups become unnecessary",
  ],
  "recovery-plan": [
    "A device is lost. Which preparation can make restoring data possible?",
    "A separate usable backup and working recovery options",
    "A backup stored only on the lost device",
    "An unsaved tab on the lost device",
  ],
  "absolute-relative": [
    "An invented rate falls from 8 in 100 to 4 in 100. What is its relative reduction?",
    "50%",
    "4%",
    "100%",
  ],
  "base-rates": [
    "In an invented group, 9 positive tests are true positives and 99 are false positives. Why do most positives not indicate the condition?",
    "There are many more false positives than true positives in this group",
    "Every positive test is automatically true",
    "The nine true positives outnumber the 99 false positives",
  ],
  "sampling-bias": [
    "A large voluntary website poll omits people who never visit the site. Why can adding more site respondents fail to fix this?",
    "The selection process can remain unrepresentative",
    "Any sample over 100 must represent everyone",
    "Response count alone defines the target population",
  ],
  correlation: [
    "Ice-cream sales and swimming both rise in hot weather. What does this pattern alone fail to prove?",
    "That buying ice cream causes swimming",
    "That the two measured activities vary",
    "That a third factor could matter",
  ],
};
for (const [id, [question, ...options]] of Object.entries(applications)) {
  const p = extraPrompts.find((p) => p.id === id + "-1");
  p.question = question;
  p.options = [options[1], options[0], options[2]];
  p.answer = 1;
}

extraSources.house = [
  "US House of Representatives · Representatives",
  "https://www.house.gov/representatives",
];
extraSources.sunk = [
  "Federal Reserve Bank of St. Louis · Thinking like an economist",
  "https://www.stlouisfed.org/open-vault/2020/march/three-ways-think-like-an-economist",
];
extraConcepts.find((c) => c.id === "house-senate").sources.push("house");
extraConcepts.find((c) => c.id === "sunk-cost").sources = ["sunk"];
